### ISSUE TITLE
webpack build error. Module not found: Can't resolve '@rrule-rust/lib-android-arm-eabi'

### ISSUE THREAD

**Issue by shxlsp** [lsndr/rrule-rust#17]
<img width="985" alt="image" src="https://github.com/lsndr/rrule-rust/assets/40187138/27ebe3d4-fc03-4904-9408-a842634ee5f7">

I don't know how to run this package, it reported errors in webpack packaging, and it also reported errors in my project running.

**Comment by lsndr** [comment]
@shxlsp could you provide the full log including command which you used to install the package? Also please specify the OS version you use
